### ISSUE TITLE
Backend should return a user object during replacingIds

### ISSUE THREAD

**Issue by davethenipper** [YashdalfTheGray/flintandsteel#187] opened 2015-12-02 03:53 UTC
Change author id, member id and everything else to user id

**Comment by YashdalfTheGray** [comment] 2015-12-02 16:17
I think authorId, memberId and things like that should be kept, they aren't unique, only the userId they refer to is unique and they give context to the data. A userId attached to an idea is ambiguous while an authorId attached to an idea tells you exactly why that piece of data exists.

**Comment by Mctalian** [comment] 2015-12-02 16:29
It also adds confusion to our developers. I've had to explain this stuff
weekly. I prefer consistency as far as this goes. My opinion, anyway.

**Comment by YashdalfTheGray** [comment] 2015-12-02 16:38
Wait...how hard is it to know that an authorId is going to refer to a user?! If we can't even make that assumption, I think we all need to stop and go back to like software design 101 first.

**Comment by Mctalian** [comment] 2015-12-02 16:53
It's the ID replacement, not what the authorId, memberId, userId represent. Everyone understands what an author is. Everyone understands what a member is. They are all users. The problem comes in when you have an authorId, the server provides you with an author object with the name, email, etc. When you have a memberId, the server provides you with a member object with the same info. And same with userId and user object. So those are all remaining consistent within their context, but it's inconsistent across the board and the ID replacement (more appending than replacing) has been confusing to some.

Is it difficult for me to understand? No, I wrote it. It's pretty typical to have blinders on when you are the creator, or a core contributor to a project. I'm merely keeping an open mind for the developers for which this stuff is not as clear and placing a momento here to address this concern in some way.

If we want to remove the "bug" label, that's fine, but I think this should be addressed in a way that's not "You should just know." If we need a Lunch and Learn, so be it, but it needs to be addressed somehow, for the sake of maintainability.

**Comment by YashdalfTheGray** [comment] 2015-12-02 17:02
The server shouldn't provide you with an author object, it should provide you with a user object, granted it's all the same, just depends on what you want to call it in code. It is all the same object. 

I'm also not saying "you should just know" but there is a minimum amount of javascript/angular experience required for this project, it's not a starter and it's not a tutorial, there are other projects out there for that purpose; this is NOT it. It's up to the developer to make sure that they have enough knowledge to be able to be comfortable. It's not the project's job to make a contributor comfortable, it's their job to make themselves comfortable within the project. 

If they are not willing to put in the work to learn and become comfortable with how the code works, they have no right to contribute to this project.

**Comment by Mctalian** [comment] 2015-12-02 17:59
Changed title.

**Comment by Mctalian** [comment] 2015-12-15 00:15
@YashdalfTheGray, any chance this is included in your back-end work? Or should I plan on picking this up once you finish up. Keep in mind there's going to be a lot of client-side residual damage if you make this change. I would also recommend changing the returned "user" or "author" object's "mail" field to "email". If nothing else I'm reminding future me, because his memory seems to be a little shot these days.

**Comment by YashdalfTheGray** [comment] 2015-12-15 01:01
Do you think we should do this? My thoughts on this issue was about replaceIds and I'm convinced that we need the replaceIds functionality for sure. Do you think we need to call the member object user globally?

**Comment by Mctalian** [comment] 2015-12-15 01:16
It's not hurting us the way it is now. It's definitely not a bug, so I'm
fine with just closing this. A minor thing and something users won't ever
even notice.

**Comment by YashdalfTheGray** [comment] 2015-12-15 01:30
Yeah, I'm pretty okay with closing this as well!

**Closed by YashdalfTheGray** 2015-12-15 01:30 UTC
Labels: bug
