### ISSUE TITLE
As a developer I want a language filter so that users cannot as easily say inappropriate comments

### ISSUE THREAD

**Issue by davethenipper** [YashdalfTheGray/flintandsteel#234] opened 2016-01-11 21:10 UTC
Acceptance Criteria:
- [ ] To Come

This could be Phase 2 or 3.  Not high priority.

**Comment by YashdalfTheGray** [comment] 2016-01-26 23:06
Closing because duplicate of #217.

**Closed by YashdalfTheGray** 2016-01-26 23:06 UTC
Labels: User Story
